version: '3'

networks:
  front:
    driver: bridge
  back:
    driver: bridge
    internal: true

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: bitnami_wordpress
      WORDPRESS_DB_USER: bn_wordpress
      WORDPRESS_DB_PASSWORD: bitnami
      WORDPRESS_BLOG_NAME: "User's blog"
      WORDPRESS_USERNAME: user
      WORDPRESS_PASSWORD: bitnami
      WORDPRESS_EMAIL: user@example.com
    depends_on:
      - db
    restart: always
    networks:
      - front
      - back

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: bitnami
      MYSQL_DATABASE: bitnami_wordpress
      MYSQL_USER: bn_wordpress
      MYSQL_PASSWORD: bitnami
    restart: always
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: bitnami
    depends_on:
      - db
    restart: always
    networks:
      - front
      - back
