version: '3'

networks:
  front:
    driver: bridge
  back:
    driver: bridge
    internal: true

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: bitnami_wordpress
      WORDPRESS_DB_USER: bn_wordpress
      WORDPRESS_DB_PASSWORD: bitnami
      WORDPRESS_BLOG_NAME: "Juan blog"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - front
      - back

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bitnami
      MYSQL_DATABASE: bitnami_wordpress
      MYSQL_USER: bn_wordpress
      MYSQL_PASSWORD: bitnami
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: bitnami
    depends_on:
      - db
    restart: always
    networks:
      - front
      - back